import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { matches } from "@/lib/mock-data";
import { ScoreRing } from "./index";

export const Route = createFileRoute("/matches/$matchId")({
  component: MatchDetail,
  loader: ({ params }) => {
    const m = matches.find((x) => x.id === params.matchId);
    if (!m) throw notFound();
    return { match: m };
  },
  notFoundComponent: () => (
    <div className="min-h-screen flex items-center justify-center"><div>Match not found · <Link to="/matches" className="text-electric underline">Back</Link></div></div>
  ),
  errorComponent: ({ error }) => <div className="p-10">Error: {error.message}</div>,
  head: ({ loaderData }) => ({ meta: [{ title: `${loaderData?.match.talent.name} ↔ ${loaderData?.match.startup.name} — LaunchHive` }] }),
});

function MatchDetail() {
  const { match: m } = Route.useLoaderData() as { match: typeof matches[number] };
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="container-x py-10 flex-1">
        <Link to="/matches" className="text-xs font-mono uppercase tracking-wider text-muted-foreground hover:text-foreground">← Match queue</Link>

        <div className="mt-6 grid lg:grid-cols-[1.3fr_1fr] gap-6 items-start">
          {/* Left main */}
          <div className="space-y-6">
            <div className="card-surface p-8">
              <div className="flex items-start gap-5">
                <ScoreRing score={m.score} />
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="chip" style={{ color: "var(--signal)", borderColor: "color-mix(in oklab, var(--signal) 40%, transparent)" }}>{m.confidence} confidence</span>
                    <span className="chip">{m.talent.archetype} → {m.startup.sector}</span>
                  </div>
                  <h1 className="font-display text-4xl md:text-5xl mt-4 leading-tight">
                    {m.talent.name}
                    <span className="block text-muted-foreground font-normal text-2xl mt-1">↔ {m.startup.name}</span>
                  </h1>
                  <p className="mt-4 text-muted-foreground">{m.talent.headline}</p>
                </div>
              </div>
            </div>

            <Section title="Why this match" subtitle="Generated by Gemini, grounded in the Utah Eco Agent.">
              <ol className="space-y-3">
                {m.reasons.map((r, i) => (
                  <li key={i} className="flex gap-4 p-4 rounded-lg bg-surface-elevated/50 border border-border/60">
                    <span className="font-mono text-electric text-sm pt-0.5">{String(i + 1).padStart(2, "0")}</span>
                    <span className="text-sm leading-relaxed">{r}</span>
                  </li>
                ))}
              </ol>
            </Section>

            <Section title="Gap analysis" subtitle="Not a dealbreaker — a known unknown to address.">
              <div className="space-y-3">
                {m.gaps.map((g, i) => (
                  <div key={i} className="flex gap-3 p-4 rounded-lg border border-bond/30 bg-bond/5">
                    <span className="text-bond mt-0.5">⚠</span>
                    <span className="text-sm">{g}</span>
                  </div>
                ))}
              </div>
            </Section>

            <Section title="Suggested next steps" subtitle="Concrete actions, not 'connect on LinkedIn'.">
              <div className="space-y-3">
                {m.nextSteps.map((s, i) => (
                  <div key={i} className="flex items-center justify-between gap-3 p-4 rounded-lg bg-surface-elevated/50 border border-border/60">
                    <div className="flex gap-3 items-center">
                      <span className="size-7 rounded-full bg-electric/15 text-electric grid place-items-center text-xs font-mono">{i + 1}</span>
                      <span className="text-sm">{s}</span>
                    </div>
                    {i === 0 && <button className="btn-primary text-xs hover:[filter:brightness(1.08)]">Request intro</button>}
                  </div>
                ))}
              </div>
            </Section>

            <Section title="Match scoring breakdown">
              <div className="space-y-4">
                {[
                  { k: "Skill overlap", v: 92 },
                  { k: "Stage alignment", v: 95 },
                  { k: "Risk tolerance", v: 88 },
                  { k: "Mission alignment", v: 96 },
                  { k: "Ecosystem proximity", v: 84 },
                  { k: "Commercialization fit", v: 90 },
                ].map((s) => (
                  <div key={s.k}>
                    <div className="flex justify-between text-sm">
                      <span>{s.k}</span>
                      <span className="font-mono text-muted-foreground">{s.v}</span>
                    </div>
                    <div className="h-1.5 bg-input rounded-full mt-1.5 overflow-hidden">
                      <div className="h-full bg-gradient-to-r from-electric to-signal" style={{ width: `${s.v}%` }} />
                    </div>
                  </div>
                ))}
              </div>
            </Section>
          </div>

          {/* Right rail */}
          <aside className="space-y-6 lg:sticky lg:top-24">
            <div className="card-surface p-6">
              <div className="text-xs font-mono uppercase tracking-wider text-muted-foreground">Startup</div>
              <h3 className="font-display text-2xl mt-2">{m.startup.name}</h3>
              <p className="text-sm text-muted-foreground mt-2">{m.startup.oneLiner}</p>
              <p className="text-sm mt-4 text-foreground/80 leading-relaxed">{m.startup.description}</p>
              <dl className="mt-5 grid grid-cols-2 gap-3 text-xs">
                {[
                  ["Origin", m.startup.origin],
                  ["TRL", `${m.startup.trl} / 9`],
                  ["Stage", m.startup.fundingStage],
                  ["Team", `${m.startup.team} ppl`],
                  ["Regulatory", m.startup.regulatory],
                  ["Funding", m.startup.funding],
                ].map(([k, v]) => (
                  <div key={k as string}>
                    <dt className="font-mono uppercase tracking-wider text-muted-foreground text-[10px]">{k}</dt>
                    <dd className="mt-0.5">{v}</dd>
                  </div>
                ))}
              </dl>
              <div className="mt-5 pt-5 border-t border-border/60">
                <div className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground mb-2">Utah programs</div>
                <div className="flex flex-wrap gap-1.5">
                  {m.startup.utahPrograms.map((p) => <span key={p} className="chip" style={{ color: "var(--bond)", borderColor: "color-mix(in oklab, var(--bond) 40%, transparent)" }}>{p}</span>)}
                </div>
              </div>
              <div className="mt-5 pt-5 border-t border-border/60">
                <div className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground mb-2">Immediate needs</div>
                <ul className="space-y-1 text-sm">
                  {m.startup.needs.map((n) => <li key={n} className="flex gap-2"><span className="text-electric">•</span>{n}</li>)}
                </ul>
              </div>
            </div>

            <div className="card-surface p-6">
              <div className="text-xs font-mono uppercase tracking-wider text-muted-foreground">Talent</div>
              <h3 className="font-display text-2xl mt-2">{m.talent.name}</h3>
              <p className="text-sm text-muted-foreground mt-1">{m.talent.archetype}</p>
              <dl className="mt-4 space-y-3 text-sm">
                <Row k="Availability" v={m.talent.availability} />
                <Row k="Risk" v={m.talent.riskTolerance} />
                <Row k="Comp" v={m.talent.compensation} />
                <Row k="Mission" v={m.talent.mission} />
              </dl>
              <div className="mt-5 pt-5 border-t border-border/60">
                <div className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground mb-2">Ecosystem signals</div>
                <ul className="space-y-1 text-sm">
                  {m.talent.ecosystemSignals.map((s) => <li key={s} className="flex gap-2"><span className="text-signal">✓</span>{s}</li>)}
                </ul>
              </div>
            </div>
          </aside>
        </div>
      </main>
      <Footer />
    </div>
  );
}

function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <div className="card-surface p-8">
      <div className="flex items-baseline justify-between gap-4 flex-wrap">
        <h2 className="font-display text-2xl">{title}</h2>
        {subtitle && <p className="text-xs text-muted-foreground font-mono uppercase tracking-wider">{subtitle}</p>}
      </div>
      <div className="mt-5">{children}</div>
    </div>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div>
      <dt className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">{k}</dt>
      <dd className="mt-0.5">{v}</dd>
    </div>
  );
}
