/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/how-it-works': typeof HowItWorksRoute
  '/matches': typeof MatchesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/how-it-works': typeof HowItWorksRoute
  '/matches': typeof MatchesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/how-it-works': typeof HowItWorksRoute
  '/matches': typeof MatchesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecosystem'
    | '/how-it-works'
    | '/matches'
    | '/onboarding'
    | '/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecosystem'
    | '/how-it-works'
    | '/matches'
    | '/onboarding'
    | '/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/ecosystem'
    | '/how-it-works'
    | '/matches'
    | '/onboarding'
    | '/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcosystemRoute: typeof EcosystemRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
  }
}

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcosystemRoute: EcosystemRoute,
  HowItWorksRoute: HowItWorksRoute,
  MatchesRoute: MatchesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
